<?php


namespace App\Presenters;


use App\Entity\Train;
use Nette\Application\UI\Presenter;

class TrainPresenter extends Presenter {

	private $storage;
	private $ipGeoApi = 'https://api.ipgeolocation.io/ipgeo?apiKey=__APIKEY__&ip=__IPADDRESS__';
	private $apiKey = 'a05f2a7b723140b994db4d3c8e5545a6';
	public function __construct(
		Storage $storage
	) {
		$this->storage = $storage;
	}

	public function beforeRender() {
		parent::beforeRender(); // TODO: Change the autogenerated stub
		$this->template->version = file_get_contents(__DIR__ . '/../../www/version');
	}

	public function actionDefault() {
		$this->template->data = $this->storage->getTrainScore();
	}

	public function actionAdd($score) {
		$train = new Train();
		$train->date = date("Y-m-d H:i:s");
		$train->score = $score;

		$info = $this->geolocate();
		if(count($info) == 0) {
			$train->user = 'Neznámý uživatel';
		} else {
			$train->ip_address = $info->ip;
			$train->countery_flag = $info->country_flag;
			$train->user = 'Hráč z města ' . $info->city;
		}
		$this->storage->writeScore($train);
		$this->sendJson(array('ok' => true));
	}


	private function geolocate() {
		$ip = $this->getHttpRequest()->getRemoteAddress();
		$requst = str_replace('__APIKEY__',$this->apiKey,$this->ipGeoApi);
		$requst = str_replace('__IPADDRESS__',$ip,$requst);
		$json = file_get_contents($requst);
		return (object)json_decode($json);
	}

}